#!/bin/python3

#We are going  to make a gradebook to orginze the subjects using python


previous_semester_gradebook = [("politics", 80), ("latin", 96), ("dance", 97), ("architecture", 65)]

subjects = ["physics", "calculus", "poetry", "history",]

grades = [98, 97, 85, 88]

subjects.append("computer science")

grades.append(100)

gradebook = list(zip(subjects, grades))

gradebook.append(("visual arts", 93))

full_gradebook = previous_semester_gradebook + gradebook

print (gradebook, full_gradebook)

